# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{symbolize}
  s.version = "4.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2011-09-22}
  s.description = %q{ActiveRecord/Mongoid enums with i18n}
  s.email = %q{x@nofxx.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/symbolize.rb",
    "lib/symbolize/active_record.rb",
    "lib/symbolize/mongoid.rb",
    "lib/symbolize/railtie.rb",
    "lib/symbolize/symbolize_helper.rb",
    "spec/db/001_create_testing_structure.rb",
    "spec/locales/en.yml",
    "spec/locales/pt.yml",
    "spec/spec_helper.rb",
    "spec/spec_helper_ar.rb",
    "spec/spec_helper_mongoid.rb",
    "spec/symbolize/active_record_spec.rb",
    "spec/symbolize/mongoid_spec.rb",
    "spec/symbolize_spec.rb",
    "symbolize.gemspec"
  ]
  s.homepage = %q{http://github.com/nofxx/symbolize}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Object enums with i18n in AR or Mongoid}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

